###
#journal_size: 5120
#max_open_files: 131072
#osd_pool_default_size: 3
#osd_pool_default_min_size: 2
#osd_recovery_op_priority: 2
#osd_recovery_max_active: 2
#osd_max_backfills: 1

parameter_defaults:
  CinderBackupBackend: ceph
  CephPoolDefaultSize: 3
  CephConfigOverrides:
    osd_pool_default_pg_num: 64
    osd_pool_default_pgp_num: 64
    ### Added because of https://bugzilla.redhat.com/show_bug.cgi?id=1477348
    osd_mkfs_options_xfs: '-f -d agcount=24'
  CephPools:
    - name: volumes
      pg_num: 64 
      application: rbd
    - name: vms
      pg_num: 16 
      application: rbd
    - name: images
      pg_num: 8 
      application: rbd
    - name: backups
      pg_num: 32 
      application: rbd
    - name: metrics
      pg_num: 8 
      application: openstack_gnocchi
    - name: default.rgw.buckets.index
      pg_num: 8 
      application: rgw
    - name: default.rgw.buckets.data
      pg_num: 8 
      application: rgw
  CephAnsibleDisksConfig:
    dmcrypt: false
    devices:
      - /dev/sdc
      - /dev/sdd
    osd_scenario: non-collocated
    dedicated_devices:
      - /dev/sdb
      - /dev/sdb
